Issue #SH-1218 feat : added group class
Sunbird-Ed/sunbird-client-services pull request #114
Opened 2020-10-07 05:35 UTC by swetha-aggidevara

2020-10-07 09:03 UTC, vinukumar-vs requested changes

2020-10-07 09:55 UTC, arfath-gwl commented on src/models/group/index.ts
> +export class CsGroup implements  Group {
We can't rename Group -> CsGroup or Group -> IGroup. This will break backward compatibility. IGroup is a C# convention is considered a bad Tautology in Java and TS.

2020-10-07 10:23 UTC, arfath-gwl commented on src/models/group/index.ts
> +export class CsGroup implements  Group {
Rather we can remove 'Group' as an interface and use 'Group' as the class itself, it should not be an issue with backward compatibility.

For naming conventions - IGroup is a C# convention is considered a bad Tautology in Java and TS.

2020-10-07 10:25 UTC, arfath-gwl commented on src/models/group/index.ts
> +    isGroupActive(): boolean {
we have state: 'active', having active: true is a redundancy.

2020-10-07 10:30 UTC, arfath-gwl commented on src/services/group/interface/cs-group-service.ts
> +    reactiveById(id: string, config?: CsGroupServiceConfig): Observable<CsGroupReactiveResponse>;
'reactive' is a noun with a different meaning, 'reactivate' is an action/verb and more appropriate here.

2020-10-07 12:10 UTC, arfath-gwl commented on src/models/group/index.ts
> +
Similar to Group - CsGroupActivity and CsGroupMember can be replaced with GroupActivity and GroupMember classes respectively

2020-10-08 06:04 UTC, AmiableAnil approved these changes

2020-10-08 06:09 UTC, merged